app_name: "ChatWilly"
app_version: "0.1.0"

rate_limit_max_requests: 5
rate_limit_window_seconds: 60

redis:
  enabled: false

guardrail_model:
  max_tokens: 500
  temperature: 0.1
  top_p: 1.0

response_agent_model:
  max_tokens: 2048
  temperature: 0.7
  top_p: 1.0
  max_iterations: 5

qdrant:
  url: "http://localhost:6333"
  collection_name: "chatwilly_brain"
