FROM python:3.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

COPY pyproject.toml ./
COPY README.md ./
COPY src ./src

RUN pip install .

COPY . .

CMD ["python", "main.py"]